from flask import make_response
from flask_restful import abort


class CustomExceptions():
    pass